export const Constants = {

    SET_PRACTICE_ID: 'SET_PRACTICE_ID',
    SET_PRACTICE_PART_ID: 'SET_PRACTICE_PART_ID',
    SET_OBJECT_ID: 'SET_OBJECT_ID',
    SET_PRACTICE_TYPE: 'SET_PRACTICE_TYPE',
    SET_USER: "SET_USER",
    SET_ROLE_USER: 'SET_ROLE_USER'

};