export const Constants = {
    SET_PRACTICE_ID: 'SET_PRACTICE_ID',
    SET_PRACTICE_PART: 'SET_PRACTICE_PART',
    SET_PRACTICE_PART_ID: 'SET_PRACTICE_PART_ID',
    SET_OBJECT_ID: 'SET_OBJECT_ID',
    SET_LESSON: 'SET_LESSON',
    SET_PRACTICE_TYPE: 'SET_PRACTICE_TYPE',
    SET_USER: "SET_USER",
    SET_ROLE_USER: 'SET_ROLE_USER',
    SET_LOGGED_IN: 'SET_LOGGED_IN',
    SET_ACCOUNT_ID: 'SET_ACCOUNT_ID',
    SET_QUESTION_ID: 'SET_QUESTION_ID',
    SET_QUESTIONS: 'SET_QUESTIONS',

};