FROM nginx:alpine
COPY /build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]

# 1. For build React app
    # FROM node:16.14.0 AS development
    # # Set working directory
    # WORKDIR /home/dmtrung/springBoot/project_qlbh/qlbh
    # #
    # COPY package.json /package.json
    # COPY package-lock.json /package-lock.json
    # # Same as npm install
    # RUN npm ci
    # COPY . /qlbh
    # ENV CI=true
    # ENV PORT=3000
    # CMD [ "npm", "start" ]
    # FROM development AS build
    # RUN npm run build

    # # 2. For Nginx setup
    # FROM nginx:alpine
    # # Copy config nginx
    # COPY --from=build /.nginx/nginx.conf /etc/nginx/conf.d/default.conf
    # WORKDIR /usr/share/nginx/html
    # # Remove default nginx static assets
    # RUN rm -rf ./*
    # # Copy static assets from builder stage
    # COPY --from=build /build .
    # # Containers run nginx with global directives and daemon off
    # ENTRYPOINT ["nginx", "-g", "daemon off;"]